[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start" # prisma migrate deploy handled by prestart script
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "web"
port = 3000

[services.web]
domains = ["crowecode.com", "www.crowecode.com"]